### ISSUE TITLE
NonSerialized attribute issue

### ISSUE THREAD

**Issue by kbalint** [zijianhuang/webapiclientgen#7]
Hello, first of all, thanks for this lib, really cool!
However I have found an interesting problem:

consider the following:

` 
[Serializable] 
 
public class User : BaseUser 
 
{ 

     [Required]

     public string FirstName {get; set;}

     [Required]

     public string LastName {get; set;}

     public new string UserName

     {

        get {return $"{FirstName} {LastName}"}

     }
 
} 
`
[NonSerialized] attribute can't be set here (CS0592	Attribute 'NonSerialized' is not valid on this declaration type. It is only valid on 'field' declarations.), so if I run the proxy generator (cherrypicking=4), it will generate the following for my "overridden" / hidden UserName field:

`    public class <>c : object
    {
    }
`
How can I annotate this field to hide it? Thanks

**Comment by zijianhuang** [comment]
So you get compiler error CS0592, then you just declare your POCO classes with fields rather than properties, since you prefer using Opt-out.

I had just test with "poco2ts.exe C:\VsProjects\webapiclientgen\DemoWebApi.DemoData\bin\Debug\demowebapi.demodata.dll test.ts /4"

Things just work as expected upon class UserInfoViewModel defined in this assembly.

And you did not show your whole source code, for example, have you decorate BaseUser with SerializableAttribute?

**Comment by kbalint** [comment]
Yes, the BaseUser has SerializeableAttribute. I found a workaround: in `CsPodGen.cs /TsPodGen.cs` I've changed the ` if (TypeHelper.IsClassOrStruct(type)` condition to `if (TypeHelper.IsClassOrStruct(type) && (!type.Name.StartsWith("<>")))` and all anonymous-type like notations are gone for good.

**Comment by zijianhuang** [comment]
@kbalint , but you class is not so plain and old, with the UserName property. While WebApiClientGen supports both Opt-in and Opt-out of properties, Opt-in may be better in such case, since you may just opt-in FirstName and LastName. Alternatively, you may put the IgnoreAttribute upon the UserName property.

**Comment by kbalint** [comment]
Yes, you are right: it's not so plain, but it's in use - a real life example, so IgnoreAttribute will not work either. Opt-in is okay also, but would introduce more work.

Also, I modified the generator to let all classes (both Model and ApiClient calls) be partial, and have a base class for exception handling (to get the original exception id/message from the server). I can post these changes, if interested.

**Comment by zijianhuang** [comment]
@kbalint , can you post the real life examples fully so I could test?

**Comment by zijianhuang** [comment]
no clarification from the poster.
