### ISSUE TITLE
Debug.Assert error on valid Route

### ISSUE THREAD

**Issue by kbalint** [zijianhuang/webapiclientgen#8]
In the file `\webapiclientgen\WebApiClientGen\ClientApiTsFunctionGenBase.cs` in the function `RemoveTrialEmptyString(string s) `I get a Debug.Assert error, if you have the following valid Route: '/api/admin/order/{id}/history'.  The variable 'p' must checked here. If fixed, the generated TS code works as expected.

**Comment by zijianhuang** [comment]
1. Assert is to document presumption/expectation. Not sure how this presumption is invalid, since CreateUriQuery always returns string with trial +' thus ends up with +''. The only scenario I could think of you pass a uri template in uriText directly.

2. Removing Debug.Assert won't solve any related problem, since Debug.Assert won't interrupt current work flow but write something to trace as documented at https://msdn.microsoft.com/en-us/library/kssw4w7z%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396. Besides, Debug.Assert is absent in the release build which the NuGet package is based on.

3. If the presumption is not met so p=-1. s.Remove(p, 3) will throw ArgumentOutOfRangeException anyway.

So @kbalint , please post your code example so I would test and examine if the current presumption is valid. I need to make sure the changes will cover bot existing scenarios and your scenarios.

**Comment by zijianhuang** [comment]
no clarification from the poster.
